apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  type: NodePort
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 30090
  selector:
    app: prometheus

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: config-volume
              mountPath: /etc/prometheus/
      volumes:
        - name: config-volume
          configMap:
            name: prometheus-config

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'kafka-exporter'
        static_configs:
          - targets: ['kafka-exporter:9308']

      - job_name: 'elasticsearch-exporter'
        static_configs:
          - targets: ['elasticsearch-exporter:9108']

      - job_name: 'wiki-producer'
        static_configs:
          - targets: ['wiki-producer:8001']

      - job_name: 'wiki-stream-processor'
        static_configs:
          - targets: ['wiki-stream-processor:8001']

      - job_name: 'node-exporters'
        static_configs:
          - targets:
              - '172.19.0.5:9100'  # Replace with actual node IPs, or use service discovery

      - job_name: 'kafka-connect-exporter'
        static_configs:
          - targets: ['kafka-connect-exporter:9404']
